### ISSUE TITLE
Add styled-components GlobalFonts

### ISSUE THREAD

**Issue by redapy** [casbah-ma/hotel-ui#11]
## is your feature request related to a problem? Please describe:

- Currently, the consumer of this library can provide global colors (theme) by passing the theme prop to the <HotelUiProvider />, which is great. However, global fonts are configured from the tailwind config.
- That applies that the user has to define global theming in two different places.
## Describe the solution you'd like:

- A good solution for this would be having GlobalFonts, provided by `styled-components` as well. We can follow [this example](https://gitlab.com/casbah/casbah-projects/smit-program/hotels-cms/hotel-staff-webapp/-/tree/master/src/components/GlobalFonts)

**Comment by redapy** [comment]
@Ysrbolles is it done?

**Comment by Ysrbolles** [comment]
@redapy Yes it's done, and worked !

**Comment by redapy** [comment]
@Ysrbolles thanks!
