### ISSUE TITLE
Navbar issue

### ISSUE THREAD

**Issue by khaoulazouggar** [casbah-ma/hotel-ui#59]
### Description

Navbar do not appear when using safari

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Hotel UI Version

0.4.0

### Browser

Safari

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

https://user-images.githubusercontent.com/47794335/193307037-a19f03c6-fe35-4b3b-9feb-b3fc557ea1b4.mov

**Comment by redapy** [comment]
@khaoulazouggar  it works fine for me! what safari version are you using?


https://user-images.githubusercontent.com/85396770/194514598-55d8cc5b-8fc4-4a07-b0cd-11210536d7c2.mov

**Comment by khaoulazouggar** [comment]
@redapy yahya who found the problem but i have the same problem in Manzil.
my safari version is (Version 16.0)

**Comment by redapy** [comment]
@khaoulazouggar could you please check if the problem exists on the Hotel-UI (storybook), or some specific websites?

**Comment by khaoulazouggar** [comment]
@redapy  it happen for all the navbars in hotel-ui

https://user-images.githubusercontent.com/47794335/194529582-5d412259-bace-4033-a597-2fb40ee3f0c0.mov

**Comment by redapy** [comment]
@khaoulazouggar thank you, I'll check it out.
